### ISSUE TITLE
Possiblty to filter out Closed issues when you list up available ones

### ISSUE THREAD

**Issue by megyof** [ZalaPanda/redmine-time-spender#3]
I believe we should have a simple configuration possibility to exclude closed issues or not when plugin displays possible issues under a project
![image](https://user-images.githubusercontent.com/17219013/148771883-ce4714ac-8fd5-408e-9404-f13981701ea4.png)

In case of a big projects we can have lot of closed issues and it will be really hard to find the open ones -- usually you work on open cases :)

**Comment by ZalaPanda** [comment]
![proof](https://user-images.githubusercontent.com/26068527/152229032-bdb7afc5-900a-4214-ab67-c28d0151159a.png)  
Feature added in [v1.1.0](https://github.com/ZalaPanda/redmine-time-spender/releases/tag/v1.1.0)
